// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import { rehypeDocLinks } from './plugins/rehype-doc-links.mjs';

// Served from a subpath, so this has to match the repo name.
const base = '/core';

// https://astro.build/config
export default defineConfig({
	// Deployed to GitHub Pages at https://bferg314.github.io/core
	site: 'https://bferg314.github.io',
	base,

	markdown: {
		// Lets pages link to each other by relative file path, and fails the
		// build on a link whose target is missing. See the plugin for details.
		rehypePlugins: [[rehypeDocLinks, { base, docsDir: 'src/content/docs' }]],
	},

	integrations: [
		starlight({
			title: 'Core',
			description:
				'A personal knowledge base: technical how-tos, machine setup runbooks, and things worth thinking about.',

			// `theme.css` retints the site-wide palette; `landing.css` styles the
			// splash page and is scoped to the `[data-has-hero]` attribute that
			// Starlight only sets on pages with a `hero` in their frontmatter.
			customCss: ['./src/styles/theme.css', './src/styles/landing.css'],
			social: [
				{ icon: 'github', label: 'GitHub', href: 'https://github.com/bferg314/core' },
			],

			// Shows a "Last updated" date on each page, read from git history.
			lastUpdated: true,

			// Adds an "Edit page" link at the bottom of every page.
			editLink: {
				baseUrl: 'https://github.com/bferg314/core/edit/main/',
			},

			// Every section is autogenerated from its directory, so adding a new
			// page is just dropping a Markdown file in the right folder. Control
			// ordering within a section with `sidebar.order` in the frontmatter.
			sidebar: [
				{
					label: 'Machine Setup',
					items: [{ autogenerate: { directory: 'setup' } }],
				},
				{
					label: 'How-To',
					items: [{ autogenerate: { directory: 'howto' } }],
				},
				{
					label: 'Cheatsheets',
					items: [{ autogenerate: { directory: 'cheatsheets' } }],
				},
				{
					label: 'Philosophy',
					items: [{ autogenerate: { directory: 'philosophy' } }],
				},
				{
					label: 'Meta',
					collapsed: true,
					items: [{ autogenerate: { directory: 'meta' } }],
				},
			],
		}),
	],
});
